# Executive AI Assistant Configuration for Patrick Smith
# This configuration file controls how EAIA handles your emails

# Primary email account to monitor
email: patrick@highline.work

# Default AI model to use
model: gpt-4o

# Personal information
full_name: Patrick Smith
name: Patrick
background: |
  Patrick is a technology executive and entrepreneur focused on AI and software development.
  He works with various AI projects and maintains both professional (patrick@highline.work) 
  and personal (patrick.smith@gmail.com) email accounts.

# Timezone for scheduling
timezone: "America/Denver"  # Adjust if different

# Calendar and scheduling preferences
schedule_preferences: |
  - Default meeting length: 30 minutes unless specified otherwise
  - Prefer morning meetings (9 AM - 12 PM)
  - Avoid scheduling on Fridays when possible
  - Buffer time between meetings: 15 minutes minimum
  - For calls, always include dial-in information or video link

# Background context for responses
background_preferences: |
  - Working on AI assistant projects and automation tools
  - Key projects: Executive AI Assistant, Finance AI Project, Clark County Permits
  - Prefer technical discussions to be precise and detailed
  - For scheduling, coordinate with existing calendar
  - Loop in relevant team members when appropriate

# Email response preferences
response_preferences: |
  - Be concise and action-oriented
  - Include relevant context from previous conversations
  - For technical topics, provide specific details and examples
  - When scheduling, always confirm timezone
  - If referencing code or technical specs, be precise
  - End emails with clear next steps when applicable

# Email tone and style preferences
rewrite_preferences: |
  Patrick's email style guidelines:
  
  - Professional but approachable tone
  - Match the sender's formality level
  - For technical discussions: precise and detailed
  - For business discussions: concise and action-oriented
  - With familiar contacts: more casual and direct
  - Avoid overly formal language unless context requires it
  - Use bullet points for multiple items or action points
  - Sign offs: "Best," or "Thanks," for most emails
  - Skip greetings/sign-offs for quick internal exchanges

# Emails to ignore/archive automatically
triage_no: |
  - Marketing emails and promotional content
  - Newsletter subscriptions (unless from key industry sources)
  - Automated service notifications (except critical security alerts)
  - Cold sales outreach without specific relevance
  - Social media notifications
  - Spam and phishing attempts
  - Automated GitHub notifications (except for direct mentions or assigned issues)
  - Generic recruitment emails
  - Event invitations without personal connection

# Emails to notify about (but not respond to)
triage_notify: |
  - GitHub pull request reviews requiring action
  - Security alerts from services
  - Financial notifications (transactions, unusual activity)
  - Document sharing notifications (Google Docs, etc.)
  - Meeting invitations requiring response
  - Emails from family members
  - Urgent system alerts or downtime notifications
  - Legal or compliance-related communications
  - Emails marked as "High Priority" from known contacts

# Emails to draft responses for
triage_email: |
  - Direct questions requiring Patrick's input
  - Meeting scheduling requests
  - Technical questions about ongoing projects
  - Client or partner communications
  - Team members asking for guidance or decisions
  - Introduction requests where Patrick needs to connect people
  - Follow-ups on ongoing projects or discussions
  - Invitations to speak at events or participate in projects
  - Requests for code reviews or technical feedback
  - Personal emails from friends or colleagues requiring response
  - Any email where Patrick is explicitly asked to take action
  - Emails about Executive AI Assistant, Finance AI, or Clark County projects

# Multi-account configuration (for future enhancement)
additional_accounts:
  - email: patrick.smith@gmail.com
    type: personal
    check_frequency: 60  # minutes
    triage_rules: "Apply same rules but with more lenient filtering for personal contacts"

# Memory configuration
memory: true

# Additional settings
settings:
  # Check emails every N minutes
  check_interval: 10
  
  # Maximum emails to process per run
  max_emails_per_run: 50
  
  # Whether to send drafts for review before sending
  require_approval: true
  
  # Auto-send emails for certain categories
  auto_send_categories:
    - meeting_confirmations
    - simple_acknowledgments
  
  # VIP contacts (always notify, prioritize responses)
  vip_contacts:
    # Add important email addresses here
    # - "important@example.com"